---
- name: Install pgsql-server
  package:
    name:
      - libpq-dev
      - postgresql-9.6
      - postgresql-contrib-9.6
      - postgresql-server-dev-9.6
      - python-psycopg2
      - patch
    state: present
