---
common_packages:
  - default-jdk
  - rake
  - ruby-puppetlabs-spec-helper
  - puppet-lint
  - git
  - bundler
  - python-dev
  - python3-dev
  - jq
  - libssl-dev
  - libxml2-dev
  - libxslt-dev
  - build-essential
  - libmysqlclient-dev
  - libfreetype6-dev
  - libpng12-dev
  - git-buildpackage
  - debhelper
  - dupload
  - libffi-dev
  - libpq-dev
  - unzip
  - qemu
  - pkg-config
  - libvirt-dev
  - libsqlite3-dev
  - libldap2-dev
  - libsasl2-dev
  - python-pip
  - dh-apache2
  - dh-systemd
  - openstack-pkg-tools
  - python-sphinx
  - python3-setuptools
  - libcurl3
  - genisoimage
  - python-ceilometerclient
  - python-cinderclient
  - python-designateclient
  - python-glanceclient
  - python-heatclient
  - python-keystoneclient
  - python-neutronclient
  - python-novaclient
  - python-muranoclient
  - python-openstackclient
  - python-swiftclient
  - python-hivemind-contrib
  - python-hivemind
  - nodejs
  - libkrb5-dev
  - libaugeas-dev
  - ansible
