---
- name: Include OS-specific variables
  include_vars: "{{ var_item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml
  loop_control:
    loop_var: var_item

- name: Add cloud repository for CentOS
  yum_repository:
    name: "centos-openstack"
    description: "CentOS OpenStack"
    baseurl: "{{ openstack_repo }}"
    gpgcheck: no

- include: install.yml

- name: Remove cloud repository for CentOS
  yum_repository:
    name: "centos-openstack"
    state: absent

- include: config.yml

# Ansible 2.4 breaks the config file. We'll handle it manually with regex
- name: Disable SELinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: '^#?SELINUX='
    line: 'SELINUX=disabled'
    state: present
  when: ansible_os_family == 'RedHat'

# https://code.launchpad.net/~jordane/cloud-init/sshd-systemd-fix
- name: Fix cloud-init service dependency with SSH for CentOS 7
  copy:
    src: CentOS/7/cloud-init.service
    dest: /etc/systemd/system/cloud-init.service
  notify: systemctl-daemon-reload
  when: ansible_distribution_major_version == '7'

- include: services.yml

# http://blog.backslasher.net/growroot-centos.html
- name: Rebuild initramfs with growroot for CentOS 6
  shell: 'dracut -f'
  when: ansible_distribution_major_version == '6'
